<a href="https://colab.research.google.com/github/003falcon/coursework_made_easy/blob/main/algos4training/BackProp_algo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

In [2]:
# Activation functions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

##Training

In [71]:


# Inputs (a, b, c)
X = np.array([
    [1, -5, 6],   # Pattern 1
    [1, -6, 8]    # Pattern 2
])

# Desired outputs (roots)
y = np.array([
    [2, 3],   # Roots of x^2 - 5x + 6 = 0
    [2, 4]    # Roots of x^2 - 6x + 8 = 0
])



# Initialize weights/biases
np.random.seed(42)
input_size = X[0].shape[0]
hidden_size = 5
output_size = y[0].shape[0]

wij=np.array(
    [[0.2,-0.9,0.3,-0.4,0.1],
    [-0.1,0.2,-0.7,0.6,-0.5],
    [0.8,-0.7,0.4,-0.1,0.2]])


wjk=np.array(
    [[-0.1,0.2],
    [0.8,-0.7],
    [-0.3,0.5],
    [0.4,-0.3],
    [-0.2,0.1]])

# Training loop
epochs = 2
lr = 0.5

for epoch in range(epochs):

    ### Forward pass
    netj = wij.T.dot(X[epoch].T)
    # print(netj.shape)

    oj = sigmoid(netj)
    # print(oj)

    oj_deriv=sigmoid_derivative(oj)
    # print(oj_deriv)

    netk=wjk.T.dot(oj)
    # print(netk)

    ok=sigmoid(netk)
    # print(ok)

    ok_deriv=sigmoid_derivative(ok)
    # print(ok_deriv)

    output = ok  # linear output

#     # Error
    error = y[epoch] - output
    # print(error.shape,oj.shape,ok_deriv.shape)


    ### Backward pass
    del_k = error*ok_deriv #just multiply element wise
    del_wjk=np.outer(oj,del_k)
    del_wjk*=lr
    print("change in weights of hidden layer")
    print(del_wjk)

    del_wij = np.matmul(wjk,del_k)
    # print(del_wij)
    del_wij*=oj_deriv*lr
    del_wij=np.outer(X[epoch],del_wij)
    # print(del_wij)

    wij+=del_wij
    wjk+=del_wjk
    print("Input layer updated weights")
    print(wij)
    # print(wjk)


# print(output)

change in weights of hidden layer
[[0.187885 0.247337]
 [0.000422 0.000556]
 [0.188271 0.247844]
 [0.003393 0.004467]
 [0.184525 0.242913]]
Input layer updated weights
[[ 0.200125 -0.900051  0.300137 -0.399983  0.099724]
 [-0.100624  0.200256 -0.700683  0.599915 -0.49862 ]
 [ 0.800749 -0.700307  0.40082  -0.099899  0.198344]]
change in weights of hidden layer
[[0.188412 0.232071]
 [0.000085 0.000105]
 [0.188466 0.232138]
 [0.001541 0.001898]
 [0.186814 0.230103]]
Input layer updated weights
[[ 0.200214 -0.900056  0.300205 -0.399923  0.100424]
 [-0.101158  0.200287 -0.701093  0.599554 -0.502821]
 [ 0.801461 -0.700349  0.401366 -0.099417  0.203945]]


##Testing


In [65]:
X_test=[[1,-5.5,7]]
for epoch in range(len(X_test)):
### Forward pass
    netj = wij.T.dot(X[epoch].T)
    # print(netj.shape)

    oj = sigmoid(netj)
    # print(oj)

    oj_deriv=sigmoid_derivative(oj)
    # print(oj_deriv)

    netk=wjk.T.dot(oj)
    # print(netk)

    ok=sigmoid(netk)
    # print(ok)

    ok_deriv=sigmoid_derivative(ok)
    # print(ok_deriv)

    output = ok  # linear output
    print(ok)

[0.62915861 0.90103471]
