<a href="https://colab.research.google.com/github/003falcon/coursework_made_easy/blob/main/algos4training/perceptron_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Using signum activation function


In [41]:
def signum(x):
  return np.where(x>=0,1,-1)

In [56]:
import numpy as np

X1=np.array([1,-2,0,1]).reshape(-1,1)
X2=np.array([0,1.5,-0.5,-1]).reshape(-1,1)
X3=np.array([-1,1,0.5,-1]).reshape(-1,1)
X=np.array([X1,X2,X3])
# X1.resize(4,1)
# X1.shape
# X
d=[-1,-1,1]
lr=0.1
w=np.array([1,-1,0,0.5]).reshape(-1,1)
iter=2
for i in range(iter):
  print(f"iteration {i+1}\n")
  for j in range(X.shape[0]):
    print(f"pattern {j+1}")
    o1=np.round(w.T.dot(X[j]),4)
    # print(o1[0][0])
    error=np.round(d[j]-signum(o1[0][0]),4)
    # print(f"error: {error}")
    del_w=np.round(lr*error*X[j],4)
    w_new=w+del_w
    w=np.round(w_new,4)
    print(w)
    print()
print(f"Final weights {w}")

iteration 1

pattern 1
[[ 0.8]
 [-0.6]
 [ 0. ]
 [ 0.3]]

pattern 2
[[ 0.8]
 [-0.6]
 [ 0. ]
 [ 0.3]]

pattern 3
[[ 0.6]
 [-0.4]
 [ 0.1]
 [ 0.1]]

iteration 2

pattern 1
[[ 0.4]
 [ 0. ]
 [ 0.1]
 [-0.1]]

pattern 2
[[ 0.4]
 [-0.3]
 [ 0.2]
 [ 0.1]]

pattern 3
[[ 0.2]
 [-0.1]
 [ 0.3]
 [-0.1]]

Final weights [[ 0.2]
 [-0.1]
 [ 0.3]
 [-0.1]]


###Using sigmoid activation function

In [3]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [6]:
import numpy as np

X1=np.array([-0.25,0.1,-0.2]).reshape(-1,1)
X2=np.array([0.15,-0.3,0.1]).reshape(-1,1)
X=np.array([X1,X2])

d=[0.95,0.9]
lr=0.5
w=np.array([-0.3,0.2,-0.1]).reshape(-1,1)
iter=2
for i in range(iter):
  print(f"iteration {i+1}\n")
  for j in range(X.shape[0]):
    print(f"pattern {j+1}")
    net1=np.round(w.T.dot(X[j]),5)
    print(net1[0][0])
    o1=sigmoid(net1[0][0])
    o1_deriv=o1*(1-o1)
    error=np.round(d[j]-o1,5)
    print(f"error: {error}")
    del_w=lr*error*X[j]*o1_deriv
    w_new=w+del_w
    w=np.round(w_new,4)
    print(w)
    print()
print(f"Final weights {w}")

iteration 1

pattern 1
0.115
error: 0.42128
[[-0.3131]
 [ 0.2052]
 [-0.1105]]

pattern 2
-0.11958
error: 0.42986
[[-0.3051]
 [ 0.1891]
 [-0.1051]]

iteration 2

pattern 1
0.1162
error: 0.42098
[[-0.3182]
 [ 0.1943]
 [-0.1156]]

pattern 2
-0.11758
error: 0.42936
[[-0.3102]
 [ 0.1783]
 [-0.1103]]

Final weights [[-0.3102]
 [ 0.1783]
 [-0.1103]]
